### PR TITLE
Port to Python 3

### PR DESCRIPTION
**Pull request by ayushnawal**
PR includes;
* Port activity to Python 3
* Add readme file

Loved the activity :grin:

### CODE REVIEW

**Comment by ayushnawal** [comment]
@cristian99garcia,  please review!

**Comment by quozl** [comment]
Reviewed.

**Comment by cvgarciarea** [comment]
Sorry guys, I'm a little busy latelty, thanks you both.

**Comment by quozl** [comment]
Thanks!

**Pull request merged**
